[language-server.codebook]
command = "codebook-lsp"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["codebook"]
soft-wrap.enable = true

[[language]]
name = "typst"
language-servers = ["tinymist", "codebook"]
soft-wrap.enable = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]

[[language]]
name = "python"
language-servers = ["pyright"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
