[language-server.codebook]
command = "codebook-lsp"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["codebook"]
soft-wrap.enable = true

[[language]]
name = "typst"
language-servers = ["tinymist", "codebook"]
soft-wrap.enable = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]
