theme = "gruvbox-material"

[editor]
line-number = "relative"
mouse = true
scrolloff = 10

[editor.cursor-shape]
normal = "block"
insert = "block"

[editor.lsp]
enable = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"
